app/models.py
# from app import db


# class User(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.Text(), nullable=False)

#     def __repr__(self):
#         return '<User: {}>'.format(self.name)

app/forms.py
# from flask_wtf import FlaskForm
# from wtforms import StringField, PasswordField, BooleanField, SubmitField
# from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
# from app.models import User

# class LoginForm(FlaskForm):
#     username = StringField('Username', validators=[DataRequired()])
#     password = PasswordField('Password', validators=[DataRequired()])
#     remember_me = BooleanField('Remember Me')
#     submit = SubmitField('Sign In')

# class RegistrationForm(FlaskForm):
#     username = StringField('Username', validators=[DataRequired()])
#     email = StringField('Email', validators=[DataRequired(), Email()])
#     password = PasswordField('Password', validators=[DataRequired()])
#     password2 = PasswordField(
#         'Repeat Password', validators=[DataRequired(), EqualTo('password')])
#     submit = SubmitField('Register')

#     def validate_username(self, username):
#         user = User.query.filter_by(username=username.data).first()
#         if user is not None:
#             raise ValidationError('Please use a different username.')

#     def validate_email(self, email):
#         user = User.query.filter_by(email=email.data).first()
#         if user is not None:
#             raise ValidationError('Please use a different email address.')

app/__init__.py
import os
from flask import Flask
from flask_assets import Bundle, Environment



bundles = {
        'd3_viz':Bundle('map.js', 'foresight.js', 'covid-line.js',
                        'userInput-line.js', 'inputlineABC.js', 'policy_builder.js',
                        'simResult.js',
                        output='gen/main.js'),

        'home_css':Bundle('home.css',
                          output='gen/main.css'),
}

ALLOWED_EXTENSIONS = {'csv', 'xls', 'xlsx'}

def create_app():
    app = Flask(__name__)


    assets = Environment(app)
    assets.register(bundles)

    from . import models
    from . import routes

    app.register_blueprint(routes.bp)

    return app

app/routes.py
from flask import (Blueprint, flash, redirect, render_template, request,
                   url_for, jsonify, Response, send_file, make_response)
from app.COVID19master import backend
import os
import pandas as pd
import xlsxwriter

bp = Blueprint('blueprint', __name__)



@bp.route('/', methods=('GET', 'POST'))
def index():
    #return render_template('index.html')
    return render_template('policy_builder.html')


@bp.route('/download_newfile')
def download_newfile():
    path = 'results.xlsx'
    #return send_file(path, attachment_filename='results.xlsx', as_attachment=True)
    return send_file(path, attachment_filename='simulationResults.xlsx',
                     as_attachment=True, cache_timeout=0)


@bp.route('/prep_sim', methods=('GET','POST'))
def prep_sim():
    get = request.get_json() # retrieve input data from ajax request
    # if this is the first time the simulation is being run through, prep the
    # data from the front end... see line 91 where this is set as False.
    if get['new'] == 'True':
        rl_input = backend.read_ABC(get)
        # transform user inputs... will return
        results = {plan:{'is_complete':'False',
                         'remaining_decision':decision,
                         'to_java':None,
                         'pre_data':None,
                         'cost':[int(cost) for cost in get['cost']],
                         'pop_size':int(get['popSize']),
                         'init_num_inf':int(get['initialInfection']),
                         'travel_num_inf':float(get['outsideInfection']),
                         'startSim': get['start'],
                         'endSim':get['end'],
                         'state':get['state'],
                         'trans_prob':float(get['policy']['TR'][plan]) / 100}
                   for plan, decision in rl_input.items()}
    else:
    # else, if this is NOT the first time the prep_sim function is called,
    # take the partially completed simulation data and prep it.
        results = backend.prep_input_for_python(get)
    heroku = False if len(os.getcwd()) > 25 else True # set the paths
    max_time = 20 # passed to simulation as the max time to run for
    stop=False # condition to make sure simulation loop does not start another plan
    for plan, instructions in results.items(): # for plan in [A,B,C]
        if type(instructions) == dict:
            # if simulation isn't done, and stop condition not set yet
            if instructions['is_complete'] == 'False' and stop == False:
                decision = instructions['remaining_decision']
                output = backend.main_run(state=instructions['state'],
                                          decision = decision,
                                          T_max = decision.shape[0],
                                          pop_size = instructions['pop_size'],
                                          costs = instructions['cost'],
                                          init_num_inf =instructions['init_num_inf'],
                                          travel_num_inf =instructions['travel_num_inf'],
                                          startSim = instructions['startSim'],
                                          endSim = instructions['endSim'],
                                          trans_prob = instructions['trans_prob'],
                                          data=instructions['pre_data'],
                                          pre_data=instructions['to_java'],
                                          heroku=heroku,
                                          max_time=max_time)
                # ^ run simulation... will end after 15 seconds, or if simulation
                # of current plan is completed
                stop = True # set stop conditions
                results[plan] = output # save results
            else:
                # if plan has already been simulated, prep back for java
                results[plan] = backend.prep_results_for_java(results[plan])
    # check to see if all plans are simulated
    if all([v['is_complete'] == 'True' for k,v in results.items() if type(v) == dict]):
        status = 'Finished'
        inputs = backend.prep_input_excel(results)
        print(inputs)
        # Create a Pandas Excel writer using XlsxWriter as the engine.
        if heroku == False:
            writer = pd.ExcelWriter('app\\results.xlsx', engine='xlsxwriter')
        else:
            writer = pd.ExcelWriter('app/results.xlsx', engine='xlsxwriter')
        # Write each dataframe to a different worksheet.
        inputs.to_excel(writer, sheet_name='Simulation Inputs')
        pd.read_json(results['A']['to_java']).T.to_excel(writer, sheet_name='Plan A')
        if 'B' in results.keys():
            pd.read_json(results['B']['to_java']).T.to_excel(writer, sheet_name='Plan B')
        if 'C' in results.keys():
            pd.read_json(results['C']['to_java']).T.to_excel(writer, sheet_name='Plan C')
        writer.save() 
    else:
        status = 'Not Finished'
    results['status'] = status # set status
    results['new'] = 'False' # set status
    return jsonify(status='success', data=results)
    
    

app/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
  <title>COVID-19 - University Simulator</title>
  {% assets "d3_viz" %}
      <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}
  {% assets "home_css" %}
      <link rel="stylesheet" href="{{ ASSET_URL }}" />
  {% endassets %}
</head>
<meta name='viewport' content='width=device-width, height=device-height, initial-scale=1.0'>
<!-- Fonts -->
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://d3js.org/d3.v5.min.js"></script>
<script src='https://cdnjs.com/libraries/d3-legend'></script>
<script src="https://d3js.org/topojson.v1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://unpkg.com/d3-foresight"></script>
<div>
  <div class="w3-bar" style="background-color:#17202A; color:white;">
    <span class="w3-bar-item w3-display-topmiddle">COVID-19 University Simulator</span>
    <a href="{{ url_for('blueprint.index') }}" class="w3-bar-item w3-button w3-border-bottom w3-margin-right"> Home</a>
  </div>
  <div class='w3-col s12'>{% block content %}{% endblock %}</div>
  <footer class='w3-bottom-middle' style="background-color:#17202A; color:white; position: absolute; bottom: 0; width: 100%; height: 2.6rem;">
    <div class='w3-display-bottommiddle'>
    <a href='https://diseasemodeling.github.io/COVID19/' class="w3-bar-item w3-button w3-border-top"> About This Project</a>
    <a href='https://github.com/diseasemodeling/COVID19' class='w3-bar-item w3-button w3-border-top'> Our Github</a>
    <a href='https://blogs.umass.edu/chaitrag/chaitra-gopalappa/' class='w3-bar-item w3-button w3-border-top'> Our Team</a>
  </footer>
</div>

<script>

</script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class='w3-container w3-col s12' style="background-color:#34495E;" id='everything'>
    <div class="w3-panel w3-border w3-round w3-col s3 w3-blue-grey w3-margin" style='height:85vh'>
      <p> Select a State:
      <select id="selectState" onchange="updateMap()" style='width:50%'>
        <option value="New York">New York</option>
      </select></p>
      <div class='w3-row w3-border w3-dark-grey' id='holdMap'></div>
      <p> Color Map By:
      <select  name="colorState" id="colorState" onchange="updateMap()">
        <option value="positive">Cumulative Infections</option>
        <option value="totalTestResults">Number of Tests</option>
        <option value="death">Total Deaths</option>
        <option value="hospitalized">Cum. Hospitalizations</option>
        <option value="recovered">Cum. Recoveries</option>
      </select></p>
      <p> As Of:
      <input type="date" name="mapDate" id="mapDate" value='2020-05-30' onchange='updateMap()'></p>
       <p> Choose Graph Scale:
       <select id='chooseScale' onchange='updateMap()'>
         <option value='linear'>Linear</option>
         <option value='log'> Logarithmic</option>
       </select></p>
       <p> Cumulative or Daily:
       <select id='chooseCum' onchange='updateMap()'>
         <option value='cumulative'> Cumulative</option>
         <option value='daily'> Daily</option>
       </select></p>
       <a href="{{ url_for('blueprint.render_input') }}" class='w3-col w3-button w3-round w3-black'>Simulate a Policy for this State</a>
    </div>
    <div class='w3-panel w3-border w3-round w3-col s8 w3-blue-grey' style='overflow-y:scroll; height:85vh'>
      <div class=' w3-border-bottom w3-row'>
        <h1 style='text-align:center' class='w3-col s12' id=stateTitle></h1>
      </div>
      <div class='w3-col s12 w3-panel' id="graphPanel">
        <div class='w3-light-grey w3-border w3-round' id='holdInfections'></div>
        <div class='w3-panel w3-light-grey w3-border w3-round' id='holdHospitalization'></div>
        <div class='w3-light-grey w3-border w3-round' id='holdDeath'></div>
        <div class='w3-panel w3-light-grey w3-border w3-round' id='holdTest'></div>
      </div>
    </div>
</div>

<script>

console.log({{data}})

states_hash ={
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District Of Columbia': 'DC',
    'Federated States Of Micronesia': 'FM',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Marshall Islands': 'MH',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands': 'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
  }

stateDropdown()
updateMap()



function updateMap() {
  date = d3.select("#mapDate")._groups[0][0].value
  state = d3.select("#selectState")._groups[0][0].value
  document.getElementById("stateTitle").innerHTML = state
  statistic = d3.select("#colorState")._groups[0][0].value
  scaleType = d3.select("#chooseScale")._groups[0][0].value
  isCumulative = d3.select("#chooseCum")._groups[0][0].value
  date = parseFloat(date.replace(/-/g, ""))
  d3.json("https://cdn.jsdelivr.net/npm/us-atlas@3/states-albers-10m.json").then(function(map_data) {
    d3.json("https://covidtracking.com/api/v1/states/daily.json").then(function(covid_data){
      console.log(covid_data)
      makeMap('holdMap', 'mapSVG', date, statistic, map_data, covid_data)
      makeCovidTrackerLine('holdInfections', 'inf', covid_data, scaleType, state, 'positive', cumulative=isCumulative)
      makeCovidTrackerLine('holdHospitalization', 'hosp', covid_data, scaleType, state, 'hospitalized', cumulative=isCumulative)
      makeCovidTrackerLine('holdDeath', 'deat', covid_data, scaleType, state, 'death', cumulative=isCumulative)
      makeCovidTrackerLine('holdTest', 'tests', covid_data, scaleType, state, 'totalTestResults', cumulative=isCumulative)
    })
  })
}

function stateDropdown(id='selectState'){
  dropdown = document.getElementById(id)
  for (state in states_hash){
    var stateOption = new Option(state, state)
    dropdown.options.add(stateOption)
  }
}

</script>
{% endblock %}